name: build webapi

on:
  workflow_call:

env:
  API_CODE_PATH: ./src/Weather.API

jobs:
  # Build .NET application and upload artifact to workflow
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Build publishable webapp
      run: |
        dotnet publish --configuration Release
      working-directory: ${{ env.API_CODE_PATH }}

    - name: Zip publishable webapp
      run: |
        zip -r publish.zip .
      working-directory: ${{ env.API_CODE_PATH }}/bin/Release/net6.0/publish

    - name: Upload webapp as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.API_CODE_PATH }}/Release/net6.0/publish/publish.zip

