name: build webapi

on:
  workflow_call:

env:
    WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    DOTNET_VERSION: '6.0.x'             # set this to the dot net version to use    
    CODE_PATH: ./src/Weather.API

jobs:
  # Build .NET application and upload artifact to workflow
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Display dotnet version
      run: dotnet --version

    - name: .NET restore
      run: |
        dotnet restore
      working-directory: ${{ env.CODE_PATH }}

    - name: .NET build webapp
      run: |
        dotnet build --configuration Release
      working-directory: ${{ env.CODE_PATH }}

    - name: .NET publish webapp
      run: |
        dotnet publish --configuration Release -o './published-output'
      working-directory: ${{ env.CODE_PATH }}

    - name: Upload webapp as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: '${{ env.CODE_PATH }}/published-output'

