name: Build and deploy
concurrency: build-and-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # Build application.
  build:
    uses: ./.github/workflows/build.yml

  # Lint Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml
