name: Build and deploy
concurrency: build-and-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # Build application.
  build:
    uses: ./.github/workflows/build.yml

  # Lint Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  # Deploy to the dev environment.
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    needs: [build, lint]
    with:
      environmentType: Dev
      resourceGroupName: deploy.api-dev-rg
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_DEV }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
    
